"""Parse IP1100PoE autonomy EEPROM dumps (``.IPA`` files).

These ASCII-hex files are generated by ``buttonIP1100.exe`` and flashed via
IP-diagnostic.  Each file describes button→target mappings for one input
module.  See ``resources_and_docs/IPBUILDING_KNOWLEDGE.md`` §12.3–12.5.

Record layout (verified against ``10.10.1.55.IPA`` and Jan Nolf's
``devices.json`` — every record has the same 7-field shape; records are
**not** alternating button/target pairs):

    field 0..3   4 hex bytes            button id (canonical 8 hex)
    field 4      2-char decimal ASCII   target module IP last octet
    field 5      ASCII digit            target channel, tens digit
    field 6      ASCII digit or FF      target channel, units; FF = absent

Channel = ``d5 × 10 + d6``, or ``d5`` alone when field 6 is ``FF``.
Trailing ``FF`` lines are EEPROM padding and are ignored.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from pathlib import Path

from gateway.button_id import canonical_button_id

log = logging.getLogger(__name__)

# Official installer IP ranges (handleiding v6.0, knowledge §12.1).
_RELAY_OCTET_RANGE = range(30, 40)
_DIMMER_OCTET_RANGE = range(40, 50)
_INPUT_OCTET_RANGE = range(50, 60)

_TYPE_TO_MODEL = {
    "relay": "IP0200PoE",
    "dimmer": "IP0300PoE",
    "input": "IP1100PoE",
}
_DEFAULT_MAX_WATT = {"relay": 60, "dimmer": 200}


@dataclass(frozen=True)
class IpaAutonomyTarget:
    """One target on a relay or dimmer module."""

    ip: str
    channel: int


@dataclass
class IpaButtonEntry:
    """One configured pushbutton row from an IPA autonomy table."""

    button_id: str  # 8 lowercase hex chars (canonical)
    input_port: int | None = None  # not present in the IPA record
    flag: str = ""
    targets: list[IpaAutonomyTarget] = field(default_factory=list)


@dataclass
class IpaParseResult:
    """Parsed contents of one ``.IPA`` file."""

    input_ip: str
    source_path: str
    buttons: list[IpaButtonEntry] = field(default_factory=list)


def input_ip_from_ipa_filename(path: str | Path) -> str | None:
    """Return ``10.10.1.N`` when the filename looks like ``10.10.1.N.IPA``."""
    stem = Path(path).stem
    if re.fullmatch(r"\d+\.\d+\.\d+\.\d+", stem):
        return stem
    return None


def _ascii_digit_byte(value: str) -> int | None:
    if not value or value.upper() == "FF":
        return None
    try:
        v = int(value, 16)
    except ValueError:
        return None
    if 0x30 <= v <= 0x39:
        return v - 0x30
    return v


def _channel_from_fields(d5: str, d6: str) -> int | None:
    tens = _ascii_digit_byte(d5)
    if tens is None:
        return None
    if not d6 or d6.upper() == "FF":
        return tens
    units = _ascii_digit_byte(d6)
    if units is None:
        return None
    return tens * 10 + units


def parse_ipa_text(text: str) -> list[list[str]]:
    """Split IPA text into T-delimited records (typically 7 fields each)."""
    lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
    parts: list[list[str]] = []
    current: list[str] = []
    for line in lines:
        if line == "T":
            if current:
                parts.append(current)
                current = []
        else:
            current.append(line)
    if current:
        parts.append(current)
    return parts


def parse_ipa_file(path: str | Path, *, input_ip: str | None = None) -> IpaParseResult:
    """Parse one ``.IPA`` file into structured button autonomy entries."""
    resolved = Path(path)
    ip = input_ip or input_ip_from_ipa_filename(resolved) or ""
    if not ip:
        raise ValueError(
            f"Cannot determine input module IP from filename {resolved.name!r}; "
            "pass input_ip= explicitly."
        )

    records = parse_ipa_text(resolved.read_text(encoding="utf-8", errors="replace"))
    buttons: list[IpaButtonEntry] = []

    for index, fields in enumerate(records):
        if len(fields) != 7:
            log.warning(
                "Skipping IPA record %d in %s: expected 7 fields, got %d",
                index,
                resolved.name,
                len(fields),
            )
            continue
        btn_id = canonical_button_id("".join(fields[0:4]))
        if btn_id is None:
            log.warning(
                "Skipping IPA record %d in %s: unparseable button id %r",
                index,
                resolved.name,
                "".join(fields[0:4]),
            )
            continue
        try:
            ip_octet = int(fields[4])
        except ValueError:
            log.warning(
                "Skipping IPA record %d in %s: unparseable target octet %r",
                index,
                resolved.name,
                fields[4],
            )
            continue
        channel = _channel_from_fields(fields[5], fields[6])
        if channel is None:
            log.warning(
                "Skipping IPA record %d in %s: unparseable channel %r/%r",
                index,
                resolved.name,
                fields[5],
                fields[6],
            )
            continue
        target_ip = f"10.10.1.{ip_octet}"
        buttons.append(
            IpaButtonEntry(
                button_id=btn_id,
                targets=[IpaAutonomyTarget(ip=target_ip, channel=channel)],
            )
        )

    return IpaParseResult(input_ip=ip, source_path=str(resolved), buttons=buttons)


def module_type_from_ip(ip: str) -> str:
    """Guess module type from the last IP octet (installer convention §12.1)."""
    try:
        octet = int(ip.rsplit(".", 1)[-1])
    except (ValueError, IndexError):
        return "unknown"
    if octet in _RELAY_OCTET_RANGE:
        return "relay"
    if octet in _DIMMER_OCTET_RANGE:
        return "dimmer"
    if octet in _INPUT_OCTET_RANGE:
        return "input"
    return "unknown"


def build_devices_json_from_ipa(
    parsed: IpaParseResult,
    *,
    profile: str = "full",
) -> dict:
    """Build a ``devices.json``-shaped document from a parsed IPA file.

    ``profile``:
      - ``full`` (option B): all pushbuttons and all referenced target channels
        are ``active: true``.
      - ``conservative``: input pushbuttons active; only one relay channel on
        ``10.10.1.30`` active for safe first tests.
    """
    if profile not in ("full", "conservative"):
        raise ValueError(f"unknown profile: {profile!r}")

    target_channels: dict[str, set[int]] = {}
    for btn in parsed.buttons:
        for tgt in btn.targets:
            target_channels.setdefault(tgt.ip, set()).add(tgt.channel)

    modules: list[dict] = []

    pushbuttons = []
    for btn in parsed.buttons:
        entry: dict = {
            "id": btn.button_id,
            "name": f"Knop {btn.button_id}",
            "room": "Onbekend",
            "active": True,
        }
        if btn.input_port is not None:
            entry["channel"] = btn.input_port
        pushbuttons.append(entry)

    modules.append({
        "name": _TYPE_TO_MODEL["input"],
        "ip": parsed.input_ip,
        "type": "input",
        "firmware": "",
        "model": _TYPE_TO_MODEL["input"],
        "mac": "",
        "pushbuttons": pushbuttons,
        "detectors": [],
    })

    for target_ip in sorted(target_channels):
        mod_type = module_type_from_ip(target_ip)
        if mod_type == "unknown":
            continue
        model = _TYPE_TO_MODEL[mod_type]
        max_watt = _DEFAULT_MAX_WATT[mod_type]
        channels = []
        sorted_chs = sorted(target_channels[target_ip])
        for ch in sorted_chs:
            active = True
            if profile == "conservative":
                if mod_type == "relay" and target_ip == "10.10.1.30":
                    active = ch == sorted_chs[0]
                else:
                    active = False
            channels.append({
                "ch": ch,
                "name": f"Kanaal {ch}",
                "room": "Onbekend",
                "semantic_type": "light",
                "active": active,
                "max_watt": max_watt,
            })
        modules.append({
            "name": model,
            "ip": target_ip,
            "type": mod_type,
            "firmware": "",
            "model": model,
            "mac": "",
            "channels": channels,
        })

    return {"modules": modules}


def merge_devices_json(base: dict, incoming: dict) -> dict:
    """Merge ``incoming`` modules into ``base`` without clobbering operator fields."""
    modules_by_ip = {m["ip"]: dict(m) for m in base.get("modules", [])}

    for mod in incoming.get("modules", []):
        ip = mod["ip"]
        if ip not in modules_by_ip:
            modules_by_ip[ip] = mod
            continue

        existing = modules_by_ip[ip]
        mod_type = mod.get("type", existing.get("type"))

        if mod_type == "input":
            existing.setdefault("pushbuttons", [])
            existing.setdefault("detectors", [])
            known_ids = set()
            for b in existing["pushbuttons"]:
                key = canonical_button_id(str(b["id"])) or str(b["id"]).lower()
                known_ids.add(key)
            for btn in mod.get("pushbuttons", []):
                key = canonical_button_id(str(btn["id"])) or str(btn["id"]).lower()
                if key in known_ids:
                    continue
                existing["pushbuttons"].append(btn)
                known_ids.add(key)
        else:
            existing.setdefault("channels", [])
            known_ch = {c["ch"] for c in existing["channels"]}
            for ch in mod.get("channels", []):
                ch_num = ch["ch"]
                if ch_num in known_ch:
                    continue
                existing["channels"].append(ch)
                known_ch.add(ch_num)

        for key in ("name", "model", "firmware", "mac"):
            if not existing.get(key) and mod.get(key):
                existing[key] = mod[key]

    return {"modules": list(modules_by_ip.values())}
