"""Parse IP1100PoE autonomy EEPROM dumps (``.IPA`` files).

These ASCII-hex files are generated by ``buttonIP1100.exe`` and flashed via
IP-diagnostic.  Each file describes button→target mappings for one input
module.  See ``resources_and_docs/IPBUILDING_KNOWLEDGE.md`` §12.3–12.5.

Record layout (confirmed against a real ``10.10.1.55.IPA`` sample):

    [5× button-id bytes] [input port] [flag]
    T
    [4× bytes] [target IP last octet] [func1 ch] [func2 ch]
    T

Trailing ``FF`` lines are EEPROM padding and are ignored.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

# Official installer IP ranges (handleiding v6.0, knowledge §12.1).
_RELAY_OCTET_RANGE = range(30, 40)
_DIMMER_OCTET_RANGE = range(40, 50)
_INPUT_OCTET_RANGE = range(50, 60)

_TYPE_TO_MODEL = {
    "relay": "IP0200PoE",
    "dimmer": "IP0300PoE",
    "input": "IP1100PoE",
}
_DEFAULT_MAX_WATT = {"relay": 60, "dimmer": 200}


@dataclass(frozen=True)
class IpaAutonomyTarget:
    """One func1/func2 target on a relay or dimmer module."""

    ip: str
    channel: int


@dataclass
class IpaButtonEntry:
    """One configured pushbutton row from an IPA autonomy table."""

    button_id: str  # 14 lowercase hex chars (wire form, no 2D prefix)
    input_port: int
    flag: str
    targets: list[IpaAutonomyTarget] = field(default_factory=list)


@dataclass
class IpaParseResult:
    """Parsed contents of one ``.IPA`` file."""

    input_ip: str
    source_path: str
    buttons: list[IpaButtonEntry] = field(default_factory=list)


def input_ip_from_ipa_filename(path: str | Path) -> str | None:
    """Return ``10.10.1.N`` when the filename looks like ``10.10.1.N.IPA``."""
    stem = Path(path).stem
    if re.fullmatch(r"\d+\.\d+\.\d+\.\d+", stem):
        return stem
    return None


def _ascii_digit_byte(value: str) -> int | None:
    if not value or value.upper() == "FF":
        return None
    try:
        v = int(value, 16)
    except ValueError:
        return None
    if 0x30 <= v <= 0x39:
        return v - 0x30
    return v


def parse_ipa_text(text: str) -> list[tuple[list[str], list[str]]]:
    """Split IPA text into ``(part_a, part_b)`` 7-byte record pairs."""
    lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
    parts: list[list[str]] = []
    current: list[str] = []
    for line in lines:
        if line == "T":
            if current:
                parts.append(current)
                current = []
        else:
            current.append(line)
    if current:
        parts.append(current)

    pairs: list[tuple[list[str], list[str]]] = []
    i = 0
    while i + 1 < len(parts):
        a, b = parts[i], parts[i + 1]
        if len(a) == 7 and len(b) == 7:
            pairs.append((a, b))
            i += 2
        else:
            i += 1
    return pairs


def parse_ipa_file(path: str | Path, *, input_ip: str | None = None) -> IpaParseResult:
    """Parse one ``.IPA`` file into structured button autonomy entries."""
    resolved = Path(path)
    ip = input_ip or input_ip_from_ipa_filename(resolved) or ""
    if not ip:
        raise ValueError(
            f"Cannot determine input module IP from filename {resolved.name!r}; "
            "pass input_ip= explicitly."
        )

    pairs = parse_ipa_text(resolved.read_text(encoding="utf-8", errors="replace"))
    buttons: list[IpaButtonEntry] = []

    for part_a, part_b in pairs:
        btn_id = "".join(part_a[:5]).lower()
        port = _ascii_digit_byte(part_a[5])
        if port is None:
            continue
        flag = part_a[6]
        try:
            ip_octet = int(part_b[4])
        except ValueError:
            continue
        target_ip = f"10.10.1.{ip_octet}"
        targets: list[IpaAutonomyTarget] = []
        for raw_ch in (part_b[5], part_b[6]):
            ch = _ascii_digit_byte(raw_ch)
            if ch is not None:
                targets.append(IpaAutonomyTarget(ip=target_ip, channel=ch))
        buttons.append(
            IpaButtonEntry(
                button_id=btn_id,
                input_port=port,
                flag=flag,
                targets=targets,
            )
        )

    return IpaParseResult(input_ip=ip, source_path=str(resolved), buttons=buttons)


def module_type_from_ip(ip: str) -> str:
    """Guess module type from the last IP octet (installer convention §12.1)."""
    try:
        octet = int(ip.rsplit(".", 1)[-1])
    except (ValueError, IndexError):
        return "unknown"
    if octet in _RELAY_OCTET_RANGE:
        return "relay"
    if octet in _DIMMER_OCTET_RANGE:
        return "dimmer"
    if octet in _INPUT_OCTET_RANGE:
        return "input"
    return "unknown"


def build_devices_json_from_ipa(
    parsed: IpaParseResult,
    *,
    profile: str = "full",
) -> dict:
    """Build a ``devices.json``-shaped document from a parsed IPA file.

    ``profile``:
      - ``full`` (option B): all pushbuttons and all referenced target channels
        are ``active: true``.
      - ``conservative``: input pushbuttons active; only one relay channel on
        ``10.10.1.30`` active for safe first tests.
    """
    if profile not in ("full", "conservative"):
        raise ValueError(f"unknown profile: {profile!r}")

    target_channels: dict[str, set[int]] = {}
    for btn in parsed.buttons:
        for tgt in btn.targets:
            target_channels.setdefault(tgt.ip, set()).add(tgt.channel)

    modules: list[dict] = []

    pushbuttons = []
    for btn in parsed.buttons:
        pushbuttons.append({
            "id": btn.button_id,
            "channel": btn.input_port,
            "name": f"Knop {btn.input_port}-{btn.button_id[:6]}",
            "room": "Onbekend",
            "active": True,
        })

    modules.append({
        "name": _TYPE_TO_MODEL["input"],
        "ip": parsed.input_ip,
        "type": "input",
        "firmware": "",
        "model": _TYPE_TO_MODEL["input"],
        "mac": "",
        "pushbuttons": pushbuttons,
        "detectors": [],
    })

    for target_ip in sorted(target_channels):
        mod_type = module_type_from_ip(target_ip)
        if mod_type == "unknown":
            continue
        model = _TYPE_TO_MODEL[mod_type]
        max_watt = _DEFAULT_MAX_WATT[mod_type]
        channels = []
        sorted_chs = sorted(target_channels[target_ip])
        for ch in sorted_chs:
            active = True
            if profile == "conservative":
                if mod_type == "relay" and target_ip == "10.10.1.30":
                    active = ch == sorted_chs[0]
                else:
                    active = False
            channels.append({
                "ch": ch,
                "name": f"Kanaal {ch}",
                "room": "Onbekend",
                "semantic_type": "light",
                "active": active,
                "max_watt": max_watt,
            })
        modules.append({
            "name": model,
            "ip": target_ip,
            "type": mod_type,
            "firmware": "",
            "model": model,
            "mac": "",
            "channels": channels,
        })

    return {"modules": modules}


def merge_devices_json(base: dict, incoming: dict) -> dict:
    """Merge ``incoming`` modules into ``base`` without clobbering operator fields."""
    modules_by_ip = {m["ip"]: dict(m) for m in base.get("modules", [])}

    for mod in incoming.get("modules", []):
        ip = mod["ip"]
        if ip not in modules_by_ip:
            modules_by_ip[ip] = mod
            continue

        existing = modules_by_ip[ip]
        mod_type = mod.get("type", existing.get("type"))

        if mod_type == "input":
            existing.setdefault("pushbuttons", [])
            existing.setdefault("detectors", [])
            known_ids = {b["id"].lower() for b in existing["pushbuttons"]}
            for btn in mod.get("pushbuttons", []):
                if btn["id"].lower() in known_ids:
                    continue
                existing["pushbuttons"].append(btn)
                known_ids.add(btn["id"].lower())
        else:
            existing.setdefault("channels", [])
            known_ch = {c["ch"] for c in existing["channels"]}
            for ch in mod.get("channels", []):
                ch_num = ch["ch"]
                if ch_num in known_ch:
                    continue
                existing["channels"].append(ch)
                known_ch.add(ch_num)

        for key in ("name", "model", "firmware", "mac"):
            if not existing.get(key) and mod.get(key):
                existing[key] = mod[key]

    return {"modules": list(modules_by_ip.values())}
