"""Resolve the gateway release version.

Single source of truth: ``ipbuilding_gateway/config.yaml`` ``version:`` field
(required by the HA add-on manifest and CI image tags).

Resolution order:
1. ``GATEWAY_VERSION`` environment variable (optional override)
2. ``gateway/_version.py`` generated by ``prepare-build.sh`` into the Docker image
3. ``ipbuilding_gateway/config.yaml`` when running from the monorepo (pytest, local dev)
4. ``0.0.0-dev`` fallback
"""

from __future__ import annotations

import os
import re
from pathlib import Path

_CONFIG_REL = Path("ipbuilding_gateway") / "config.yaml"
_VERSION_RE = re.compile(r'^version:\s*"?([^"\n]+)"?\s*$', re.MULTILINE)


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _config_yaml_path() -> Path | None:
    candidate = _repo_root() / _CONFIG_REL
    return candidate if candidate.is_file() else None


def _parse_config_version(path: Path) -> str | None:
    match = _VERSION_RE.search(path.read_text(encoding="utf-8"))
    return match.group(1) if match else None


def resolve_version() -> str:
    override = os.environ.get("GATEWAY_VERSION", "").strip()
    if override:
        return override

    try:
        from gateway._version import __version__ as generated

        return generated
    except ImportError:
        pass

    config_path = _config_yaml_path()
    if config_path is not None:
        parsed = _parse_config_version(config_path)
        if parsed:
            return parsed

    return "0.0.0-dev"


__version__ = resolve_version()
