"""Tests for prepare-build.sh — ensures the add-on build context stays in sync.

`ipbuilding_gateway/prepare-build.sh` syncs root-level files (gateway/ and
requirements-gateway.txt) into the add-on folder so the Docker build
context has them. The root requirements file is the single source of
truth; the add-on copy is regenerated on every CI run.

This test guards against the regression we hit in v0.3.0: the root
requirements gained ``zeroconf>=0.131.0`` but the add-on copy did not,
because ``prepare-build.sh`` did not copy it. The Docker build then
ran with the stale requirements and the published image was missing
``zeroconf`` at runtime.

It also pins the v0.3.7+ invariant: there is no generated
``gateway/_version.py`` any more. The runtime version is read live
from ``ipbuilding_gateway/config.yaml`` in the add-on context, so the
Dockerfile must copy that file in and ``prepare-build.sh`` must not
stamp a generated module.
"""

from __future__ import annotations

from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[1]
ROOT_REQUIREMENTS = REPO_ROOT / "requirements-gateway.txt"
ADDON_REQUIREMENTS = REPO_ROOT / "ipbuilding_gateway" / "requirements-gateway.txt"
ADDON_GATEWAY_PKG = REPO_ROOT / "ipbuilding_gateway" / "gateway"
GENERATED_VERSION = ADDON_GATEWAY_PKG / "_version.py"
ADDON_CONFIG_YAML = REPO_ROOT / "ipbuilding_gateway" / "config.yaml"
ADDON_DOCKERFILE = REPO_ROOT / "ipbuilding_gateway" / "Dockerfile"


def test_root_requirements_exists() -> None:
    """Source of truth must exist."""
    assert ROOT_REQUIREMENTS.is_file(), (
        f"{ROOT_REQUIREMENTS} missing — this is the source of truth for "
        "gateway runtime dependencies."
    )


def test_addon_requirements_exists() -> None:
    """The build-context copy must exist (created by prepare-build.sh)."""
    assert ADDON_REQUIREMENTS.is_file(), (
        f"{ADDON_REQUIREMENTS} missing — run `ipbuilding_gateway/prepare-build.sh` "
        "to stage the file from the repo root."
    )


def test_addon_requirements_matches_root() -> None:
    """The build-context copy must mirror the root file byte-for-byte.

    If this fails after a release, the most likely cause is that someone
    updated ``requirements-gateway.txt`` in the repo root but did not
    rerun ``prepare-build.sh`` before the Docker build ran. The fix is
    to extend ``prepare-build.sh`` to copy the new file, OR to ensure CI
    runs ``prepare-build.sh`` before the build step.
    """
    root = ROOT_REQUIREMENTS.read_text(encoding="utf-8")
    addon = ADDON_REQUIREMENTS.read_text(encoding="utf-8")
    assert addon == root, (
        f"{ADDON_REQUIREMENTS} is out of sync with {ROOT_REQUIREMENTS}.\n"
        "The add-on copy is regenerated by `ipbuilding_gateway/prepare-build.sh`. "
        "Run it locally to sync, or extend the script to copy this file."
    )


def test_zeroconf_present_in_root_requirements() -> None:
    """Pinned dependency: zeroconf is required by gateway/ha_discovery.py.

    If this test fails, gateway/ha_discovery.py is using zeroconf but
    the source-of-truth requirements file is missing the dependency.
    """
    contents = ROOT_REQUIREMENTS.read_text(encoding="utf-8")
    assert "zeroconf" in contents, (
        f"{ROOT_REQUIREMENTS} must include zeroconf — used by "
        "gateway/ha_discovery.py for HA discovery broadcast."
    )


def test_no_generated_version_file_in_addon_context() -> None:
    """`gateway/_version.py` must not exist in the add-on staging copy.

    Since v0.3.7 the runtime version is read live from
    ``ipbuilding_gateway/config.yaml``; a generated file with a different
    value would silently drift Supervisor's advertised version from the
    actual one. ``prepare-build.sh`` explicitly removes any stale
    generated file before re-staging ``gateway/`` — assert that nothing
    in the build context reintroduces it.
    """
    assert not GENERATED_VERSION.exists(), (
        f"{GENERATED_VERSION} must not exist. The runtime version is read "
        "live from ipbuilding_gateway/config.yaml. If this file reappears, "
        "someone reintroduced build-time version stamping; see "
        ".cursor/rules/release-process.mdc."
    )


def test_addon_config_yaml_present_in_build_context() -> None:
    """`ipbuilding_gateway/config.yaml` must exist in the add-on context.

    The Dockerfile copies this file into the image at
    ``/app/ipbuilding_gateway/config.yaml`` so ``gateway.version`` can
    resolve it relative to the installed ``gateway/`` package. If the
    file is missing here, the Docker build context no longer carries the
    version source of truth and the runtime would report 0.0.0-dev.
    """
    assert ADDON_CONFIG_YAML.is_file(), (
        f"{ADDON_CONFIG_YAML} must exist — gateway/version.py reads the "
        "runtime version from this file in the Docker image."
    )


def test_dockerfile_copies_config_yaml_into_image() -> None:
    """The Dockerfile must COPY config.yaml into the image at runtime.

    Without this line the runtime would resolve to 0.0.0-dev in the
    container even though config.yaml is the single source of truth in
    the build context.
    """
    contents = ADDON_DOCKERFILE.read_text(encoding="utf-8")
    assert "COPY config.yaml" in contents, (
        f"{ADDON_DOCKERFILE} must COPY config.yaml into the image — "
        "the runtime version is read from there at import time."
    )
