services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant-dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: ${TZ:-Europe/Brussels}
    volumes:
      - ./config:/config
      - ${COMPANION_SRC}:/config/custom_components/ipbuilding_gateway_ha:ro
    ports:
      - "8123:8123"
    restart: unless-stopped
